### ISSUE TITLE
What is the password?

### ISSUE THREAD

**Issue by erickyun** [yuusakurisub/widevine-l3-decryptor#1]

**Comment by erickyun** [comment]
@yuusakurisub

**Comment by yuusakuri** [comment]
Maybe what you want is at the link below.
I can't tell you the password, but I think it's okay.

https://mega.nz/file/DypwzJiQ#8FbRF-bDoA303ch7N416Wl0a8Roi5__1Bd5tG6GB57g
https://forum.videohelp.com/threads/400863-Downloading-encrypted-mpd-video-files

**Comment by erickyun** [comment]
> Maybe what you want is at the link below.
> I can't tell you the password, but I think it's okay.
> 
> https://mega.nz/file/DypwzJiQ#8FbRF-bDoA303ch7N416Wl0a8Roi5__1Bd5tG6GB57g
> https://forum.videohelp.com/threads/400863-Downloading-encrypted-mpd-video-files

Thank you.🙂
